# Generated by Django 4.2.2 on 2023-07-19 21:03

from django.db import migrations, models
import travels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference_number', models.CharField(default=travels.models.booking, max_length=50, unique=True)),
                ('flight_reference_number', models.CharField(default=travels.models.make_gen_random_string, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
