# Generated by Django 4.2.2 on 2023-07-19 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking_reference_number',
            field=models.UUIDField(default=uuid.uuid5, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='flight_reference_number',
            field=models.UUIDField(default=uuid.uuid5, editable=False, unique=True),
        ),
    ]
