# Generated by Django 4.2.2 on 2023-07-21 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_alter_customer_booking_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='flight_class',
            field=models.CharField(default='Economy', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='booking_reference_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='flight_reference_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
