# Generated by Django 4.2.2 on 2023-07-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_customer_flight_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy_class', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('business_class', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('private_flight', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
    ]
