# Generated by Django 4.2.2 on 2023-07-21 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0006_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_prices',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='flight', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
