# Generated by Django 4.2.2 on 2023-07-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_customer_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.bookings'),
            preserve_default=False,
        ),
    ]
