# Generated by Django 4.2.2 on 2023-07-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_customer_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='booking',
            new_name='destination',
        ),
    ]
