# Generated by Django 4.2.2 on 2023-07-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_rename_booking_customer_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='destination',
        ),
    ]
