# Generated by Django 4.2.2 on 2023-07-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_remove_flight_prices_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
