# Generated by Django 4.2.2 on 2023-07-10 12:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=5)),
                ('ccv', models.IntegerField()),
                ('amount_on_card', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('pin', models.IntegerField(validators=[django.core.validators.MinLengthValidator(4)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amex', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
