# Generated by Django 4.2.2 on 2023-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amex',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
