# Generated by Django 4.2.2 on 2023-07-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amex', '0004_alter_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
