# Generated by Django 4.2.2 on 2023-07-15 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amex', '0005_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amex', to=settings.AUTH_USER_MODEL),
        ),
    ]
