# Generated by Django 4.2.2 on 2023-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
