# Generated by Django 4.2.2 on 2023-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='living_area',
            field=models.CharField(default='Not Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.CharField(default='Not Available', max_length=20),
        ),
    ]
