# Generated by Django 4.2.2 on 2023-07-19 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transactions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('transaction_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(default=transactions.models.return_date_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
