# Generated by Django 4.2.2 on 2023-07-15 23:17

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_history_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=transactions.models.return_date_time),
        ),
    ]
