# Generated by Django 4.2.2 on 2023-07-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_user_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
